### ISSUE TITLE
During simulation, "Error(s) in loading state_dict for MyParticleNetwork"

### ISSUE THREAD

**Issue by raynehe** [intel-isl/DeepLagrangianFluids#30]
Hi, thanks for the wonderful work!

I encountered an error when I trying to run the simulation for the canyon scene under the [instruction](https://github.com/isl-org/DeepLagrangianFluids/blob/master/scenes/README.md#1-run-the-simulation-for-the-canyon-scene). I'm using Pytorch on Ubuntu 20.04.

When I train the network from scratch, I got a list of models under `train_network_torch_default/checkpoints`, such as `ckpt-50000.pt`. Then when I run:

```bash
../scripts/run_network.py --weights ../train_network_torch_default/checkpoints/ckpt-50000.pt \
                          --scene canyon_scene.json \
                          --output canyon_out \
                          --num_steps 1500 \
                          ../scripts/train_network_torch.py
```

I got the error telling me the `.pt` file isn't correct:
```bash
Namespace(device='cuda', num_steps=1500, output='canyon_out', scene='canyon_scene.json', trainscript='../scripts/train_network_torch.py', weights='../exp_original_code/checkpoints/ckpt-50000.pt', write_bgeo=False, write_ply=False)
Traceback (most recent call last):
  File "../scripts/run_network.py", line 240, in <module>
    sys.exit(main())
  File "../scripts/run_network.py", line 236, in main
    args.num_steps, args.output, args)
  File "../scripts/run_network.py", line 110, in run_sim_torch
    model.load_state_dict(weights)
  File "/home/rayne/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1605, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MyParticleNetwork:
	Missing key(s) in state_dict: "gravity", "conv0_fluid.kernel", "conv0_fluid.bias", "conv0_fluid.offset", "conv0_obstacle.kernel", "conv0_obstacle.bias", "conv0_obstacle.offset", "dense0_fluid.weight", "dense0_fluid.bias", "dense1.weight", "dense1.bias", "conv1.kernel", "conv1.bias", "conv1.offset", "dense2.weight", "dense2.bias", "conv2.kernel", "conv2.bias", "conv2.offset", "dense3.weight", "dense3.bias", "conv3.kernel", "conv3.bias", "conv3.offset". 
	Unexpected key(s) in state_dict: "step", "model", "optimizer", "scheduler".
```

When I replace `ckpt-50000.pt` with the file `pretrained_model_weights.pt`, the command could work. I'm not sure if the `ckpt-50000.pt` file is different from the provided `pretrained_model_weights.pt` file?

I'm wondering if you could help me with it. Many thanks!

**Comment by raynehe** [comment]
Oh I found the problem. This [line](https://github.com/isl-org/DeepLagrangianFluids/blob/d651c6fdf2aca3fac9abe3693b20981b191b4769/scripts/run_network.py#L110) in the `run_network.py` should be edited as:
```python
model.load_state_dict(weights['model'])
```
